#!/usr/bin/env python3
"""
Acceptance dry-run #2 — the "plain-vs-configured / born-past-boundary" harness shape
(amirsnw xstream), exercising SEAM_A (driver-test generation) as a discrete agent step.

Unlike jadhavspeaks (pre-adaptation code exists at the parent), amirsnw was BORN past the
1.4.18 boundary and its XStream @Bean was CREATED in the fix, so there is no callable
pre-adaptation method at the parent. SEAM_A therefore emits a TWO-method driver: a plain
`new XStream()` stand-in (pre-adaptation) vs the real production `EventProcessingConfig
.xStream()` (adapted), and the harness injects an explicit depth-1 xstream dep so the
version override actually applies (xstream is transitive via Axon).

SEAM_A output below is generated by the agent from the adaptation diff + break spec; the
orchestrator then runs the 3 states deterministically and applies the oracle.
"""
import os, sys, subprocess, re, shutil
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import orchestrator as O

MVN = shutil.which("mvn") or "mvn"
GIT = shutil.which("git") or "git"
REPO = "amirsnw/chainrtrade-axon-CQRS-DDD"
ADAPT = "d408d4ca"
MODULE = "product-service"
TEST = "bbc.XstreamBbcTest"
SIGNAL = r"ForbiddenClassException: com\.chaintrade\.core\.model\.ProductRestModel"
JDK = O.JDKS["17"]

# --- SEAM_A output: derived from the adaptation diff (EventProcessingConfig.xStream() with
#     allowTypesByWildcard "com.chaintrade.core.**") and the domain type ProductRestModel.
#     Two methods = pre-adaptation stand-in vs real production config. JUnit5 (module uses jupiter).
DRIVER = r'''package bbc;

import static org.junit.jupiter.api.Assertions.assertEquals;
import com.chaintrade.core.model.ProductRestModel;
import com.thoughtworks.xstream.XStream;
import java.math.BigDecimal;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import productservice.config.EventProcessingConfig;

public class XstreamBbcTest {
    private final ProductRestModel dto =
            new ProductRestModel(UUID.randomUUID(), "widget", new BigDecimal("9.99"), 3);

    @Test
    void plainXStream() {   // pre-adaptation stand-in (Axon's default plain XStream)
        XStream x = new XStream();
        ProductRestModel back = (ProductRestModel) x.fromXML(x.toXML(dto));
        assertEquals(dto.getProductId(), back.getProductId());
    }

    @Test
    void configuredXStream() {   // the production adaptation
        XStream x = new EventProcessingConfig().xStream();
        ProductRestModel back = (ProductRestModel) x.fromXML(x.toXML(dto));
        assertEquals(dto.getProductId(), back.getProductId());
    }
}
'''

def write_test(repo_dir):
    d = os.path.join(repo_dir, MODULE, "src", "test", "java", "bbc")
    os.makedirs(d, exist_ok=True)
    open(os.path.join(d, "XstreamBbcTest.java"), "w").write(DRIVER)

def inject_xstream_dep(repo_dir):
    """Harness scaffolding: explicit depth-1 xstream dep so -Dbbc.xstream.version applies
    (otherwise xstream is pinned transitively by Axon). Idempotent."""
    pom = os.path.join(repo_dir, MODULE, "pom.xml")
    t = open(pom, encoding="utf-8").read()
    if "bbc.xstream.version" in t:
        return
    props = ("<properties><bbc.xstream.version>1.4.19</bbc.xstream.version></properties>\n"
             "    <dependencies>\n"
             "        <dependency><groupId>com.thoughtworks.xstream</groupId>"
             "<artifactId>xstream</artifactId><version>${bbc.xstream.version}</version></dependency>")
    t = t.replace("<dependencies>", props, 1)
    open(pom, "w", encoding="utf-8").write(t)

def run(repo_dir, method, ver):
    env = dict(os.environ, JAVA_HOME=JDK)
    cmd = [MVN, "clean", "test", "-pl", MODULE, "-am", f"-Dtest={TEST}#{method}",
           f"-Dbbc.xstream.version={ver}", "-DargLine=-Xmx2g",
           "-Dsurefire.failIfNoSpecifiedTests=false"]
    p = subprocess.run(cmd, cwd=repo_dir, env=env, capture_output=True, text=True)
    out = p.stdout + p.stderr
    m = re.search(r"Tests run: (\d+), Failures: (\d+), Errors: (\d+)", out)
    run_, fail, err = (list(map(int, m.groups())) if m else (0, 0, 0))
    return {"run": run_, "fail": fail, "err": err, "log": out}

def main():
    wd = os.path.join(os.environ.get("TEMP", "/tmp"), "bbc-acceptance")
    repo_dir = os.path.join(wd, "amirsnw")
    if os.path.isdir(os.path.join(repo_dir, ".git")):
        subprocess.run([GIT, "-C", repo_dir, "checkout", "-q", "-f", ADAPT])
    else:
        os.makedirs(wd, exist_ok=True)
        O.clone(REPO, ADAPT, repo_dir)
    write_test(repo_dir)            # SEAM_A
    inject_xstream_dep(repo_dir)    # harness scaffolding

    print("STATE 1 (plain stand-in, xstream 1.4.17) ...");  s1 = run(repo_dir, "plainXStream", "1.4.17")
    print("STATE 2 (plain stand-in, xstream 1.4.19) ...");  s2 = run(repo_dir, "plainXStream", "1.4.19")
    print("STATE 3 (production config, xstream 1.4.19) ..."); s3 = run(repo_dir, "configuredXStream", "1.4.19")

    s2_signal = bool(re.search(SIGNAL, s2["log"]))
    print("\n--- oracle ---")
    print(f"  state1 plain@1.4.17     : run={s1['run']} fail={s1['fail']} err={s1['err']}  -> {'PASS' if s1['run'] and not(s1['fail'] or s1['err']) else 'NOT-PASS'}")
    print(f"  state2 plain@1.4.19     : run={s2['run']} fail={s2['fail']} err={s2['err']}  signal={s2_signal} -> {'FAIL(+signal)' if (s2['fail'] or s2['err']) and s2_signal else 'NOT-FAIL'}")
    print(f"  state3 config@1.4.19    : run={s3['run']} fail={s3['fail']} err={s3['err']}  -> {'PASS' if s3['run'] and not(s3['fail'] or s3['err']) else 'NOT-PASS'}")
    verified = (s1["run"] and not (s1["fail"] or s1["err"]) and
                (s2["fail"] or s2["err"]) and s2_signal and
                s3["run"] and not (s3["fail"] or s3["err"]))
    print(f"\n  OUTCOME: {'verified_bbc' if verified else 'NOT verified'}")
    return 0 if verified else 1

if __name__ == "__main__":
    sys.exit(main())
